.PHONY: all kenken doc check profile

all:
	$(MAKE) -C src/

check:
	$(MAKE) check -C test/

profile:
	$(MAKE) profile -C test/

clean:
	$(MAKE) clean -C src/
	$(MAKE) clean -C test/
	$(MAKE) clean -C doc/

help:
	@echo -e "Usage: make [all]    Build all"
	@echo -e "       make check    Run coverage tests"
	@echo -e "       make profile  Run performance and load tests"
	@echo -e "       make doc      Generate documentation"
	@echo -e "       make clean    Remove all files generated by make"
	@echo -e "       make help     Display this help"
	@echo -e " "

doc:
	$(MAKE) -C doc/
